version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-latest}
        BUILD_TIME: ${BUILD_TIME}
        GIT_COMMIT: ${GIT_COMMIT}
      target: production
    image: lexicon-bo-api:${VERSION:-latest}
    container_name: lexicon-bo-api
    restart: unless-stopped

    ports:
      - "${APP_LISTEN_PORT:-8080}:8080"

    environment:
      # App Configuration
      - APP_URL=${APP_URL}
      - APP_LISTEN_HOST=0.0.0.0
      - APP_LISTEN_PORT=8080

      # Database
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      # Redis
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}

      # API Security
      - API_KEY=${API_KEY}
      - SALT=${SALT}

      # External Services
      - CHATBOT_BASE_URL=${CHATBOT_BASE_URL}
      - CHATBOT_API_KEY=${CHATBOT_API_KEY}

      # URLs
      - BASE_URL=${BASE_URL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

    networks:
      - lexicon-network

    # Security options
    security_opt:
      - no-new-privileges:true

    # Read-only root filesystem for security
    read_only: true
    tmpfs:
      - /tmp

    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  lexicon-network:
    driver: bridge
