services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: dev.Dockerfile
  #   ports:
  #     - ${APP_LISTEN_PORT}:${APP_LISTEN_PORT}
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - lexicon_bo
  postgres:
    image: "postgres:16.2"
    ports:
      - ${APP_POSTGRES_PORT}:${APP_POSTGRES_PORT}
    environment:
      POSTGRES_ROOT_PASSWORD: "${APP_POSTGRES_PASSWORD}"
      POSTGRES_ROOT_HOST: "%"
      POSTGRES_DATABASE: "${APP_POSTGRES_DB_NAME}"
      POSTGRES_USER: "${APP_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${APP_POSTGRES_PASSWORD}"
      POSTGRES_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "bo-postgres:/var/lib/postgresql/data"
    networks:
      - lexicon_bo

networks:
  lexicon_bo:
    driver: bridge

volumes:
  bo-postgres:
